services:
  test-runner:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db-postgres
    entrypoint: >
      sh -c "pytest backend/tests || exit 1"
    restart: "no"

  db-postgres:
    image: postgres
    container_name: planex-db-postgres
    environment:
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASS}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 1024mb

volumes:
  postgres_data:
