sonar.projectKey=lab-11
sonar.projectName=lab-11
sonar.projectVersion=1.0.0

sonar.login=208731730ec56b462e9f3859aff062091423d70c

sonar.projectDescription=This project demonstrates a simple node py
sonar.sources=./ 
sonar.sourceEncoding=UTF-8 