"""add task 3

Revision ID: 65bb701e8025
Revises: 968839e8cc4b
Create Date: 2025-05-09 21:10:39.193786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "65bb701e8025"
down_revision: Union[str, None] = "968839e8cc4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("titl3", sa.String(length=64), nullable=False)
    )
    op.add_column(
        "tasks",
        sa.Column(
            "statuss",
            sa.Enum(
                "todo",
                "in_progress",
                "in_review",
                "complated",
                name="taskstatus",
            ),
            nullable=False,
        ),
    )
    op.drop_column("tasks", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "status",
            postgresql.ENUM(
                "todo",
                "in_progress",
                "in_review",
                "complated",
                name="taskstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tasks", "statuss")
    op.drop_column("tasks", "titl3")
    # ### end Alembic commands ###
